### ISSUE TITLE
Quick Start refers to "Simple Agent" but there is only "Simple App" sample application

### ISSUE THREAD

**Issue by arjun-krishna1** [8090-inc/xrx-core#16]
- The docs refer to a "Simple Agent" sample application
![image](https://github.com/user-attachments/assets/82ada93a-1131-4e1f-aabc-cd16b9da7085)
- The sample apps repo has no "Simple Agent"
- It does have a "Simple App"
![image](https://github.com/user-attachments/assets/2687d1fe-5bc9-4181-b625-fdd70c3aab09)

**Comment by sinasojoodi** [comment]
@arjun-krishna1 @sabbyanandan can this be closed?

**Comment by arjun-krishna1** [comment]
> @arjun-krishna1 @sabbyanandan can this be closed?

Yes @sinasojoodi closed in https://github.com/8090-inc/xrx-core/pull/17
