### ISSUE TITLE
Sample agent repo links in readme 404'ing

### ISSUE THREAD

**Issue by JoeBerg8** [8090-inc/xrx-core#3]
Cant seem to be able to access the repos containing the sample agents/reasoning systems which is preventing me from running locally.

This projects looks very cool, thanks for sharing!

**Comment by sabbyanandan** [comment]
@JoeBerg8: Thank you for trying out! Could you expand on the issue you're facing? It'd also help if you can point to the guide that you followed. 

_(FWIW, the samples are here ->  https://github.com/8090-inc/xrx-sample-apps)_

**Comment by JoeBerg8** [comment]
Ah, makes sense. That's what I was looking for. I was following the readme in the xrx-core project. You can reproduce the 404 if you click on any of the links in `Reasoning Systems` drop down. 

Thanks!

**Comment by sabbyanandan** [comment]
You are right; how did we miss it! Thank you for pointing it out. We will fix it. Please also consider submitting a PR in the future. :)

**Comment by chrislott** [comment]
Resolved in #5
