### ISSUE TITLE
ModuleNotFoundError: No module named 'agent_framework' when running local version

### ISSUE THREAD

**Issue by kelapure** [8090-inc/xrx-core#6]
I'm encountering an error while trying to run the local version of the pizza store example. The environment is set up with the following:

- `.env` file configured
- Redis running
- Required dependencies installed

When executing the command:
`uvicorn --reload --port 8003 --env-file ../../.env main:app --log-config logging_config.yaml`

I receive the following error:

`from agent_framework import xrx_reasoning, initialize_async_llm_client
ModuleNotFoundError: No module named 'agent_framework'`

Additional details:

- I cloned the repository using the recursive flag
- I haven't been able to find a workaround for this issue yet

Steps to Reproduce:
1. Set up the environment as described
2. Run the uvicorn command mentioned above
3. Observe the ModuleNotFoundError

Expected Behavior:
The local version of the pizza store example should run without the ModuleNotFoundError.

Actual Behavior:
The application fails to start due to the missing 'agent_framework' module

**Comment by chrislott** [comment]
Already fixed in xrx-sample-apps
